name: 'oxs-package-upload'
description: 'Uploads a zip file to a Web API endpoint'
inputs:
  zip-path:
    description: 'The path to the zip file to upload'
    required: true
  api-url:
    description: 'The Web API endpoint URL'
    required: true
  api-token:
    description: 'The API authorization token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Upload to API
      shell: bash
      env:
        API_URL: ${{ inputs.api-url }}
        API_TOKEN: ${{ inputs.api-token }}
      run: |
        curl -X POST "$API_URL" \
          -H "Authorization: Bearer $API_TOKEN" \
          -F "file=@${{ inputs.zip-path }}"
